### ISSUE TITLE
.NET 5 Support

### ISSUE THREAD

**Issue by NatElkins** [ionide/Fornax#77]
**Is your feature request related to a problem? Please describe.**
Not specifically.

**Describe the solution you'd like**
.NET 5 support, and the ability to reference Nuget packages from script files.  I also think this is one way to handle themes (just package it up as a Nuget package).

**Describe alternatives you've considered**

**Additional context**

I'm mostly just creating this issue to track.  I'll try and find some time to take a crack at some point.

**Comment by baronfel** [comment]
Brief punch list to update to .net 5 and reference nuget packages would be:

* Update to FCS 38
* Add a required reference to Microsoft.Build.Utilities.Core (IIRC, might need to check FSAC for this but it's a nuget dep that's not in the FCS nuspec right now)
* Add a package reference to FSharp.DependencyManager.Nuget to get the nuget #r support implicitly, since the dll for that will be co-located with the FCS dll when you run fornax.

**Comment by baronfel** [comment]
done in #78
